#Prints new tag creation in console
logTagCreation = false
#Prints network errors in normal log rather than debug
logNetworkErrors = false
#Vanilla shrinks recipe patterns to try to optimise them, but it's sometimes breaking some modded recipes
disableRecipeShrinking = false
#Print whenever a reload is triggered
printReloadStacktrace = false
#Print whenever a command is run
printCommandStacktrace = false

